name: Deployment with 1 job
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Run build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
